name: Pages

on:
  push:
    branches:
      - test

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:

      # Checkout -----------------
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      
      # Python --------------------      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Refactor Markdownfile
        run: bash ref_markdownfile.sh

      # Hexo Image ----------------
      - name: Use Docker Image
        uses: addnab/docker-run-action@v3
        with:
            image: hsiangjenli/simslab-it-blog:2024-02-03
            platform: linux/amd64
            options: -v ${{ github.workspace }}:/app -w /app --user=root
            run: |
              sed -i 's|http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML|https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML|g' node_modules/hexo-renderer-mathjax/mathjax.html
              npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
