name: Pages

on:
  push:
    branches:
      - fix/math_render_error

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      # Checkout -----------------
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      
      # Python --------------------      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Refactor Markdownfile
        run: bash ref_markdownfile.sh

      # Hexo ----------------------
      - name: Use Node.js 17
        uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Change Mathjs URL
        run: sed -i 's|http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML|https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML|g' node_modules/hexo-renderer-mathjax/mathjax.html
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
